### ISSUE TITLE
lua5.2

### ISSUE THREAD

**Issue by hessamashari** [ANTISEC12/Conky_digilog#1]
سلام سروش.
توی readme نصب لوا برای آرچ نوشتی lua5.2.
در حالی که توی مخازن آرچ lua52 هست.
اگه حوصله داشتی عوض کن :)

**Comment by ANTISEC12** [comment]
> سلام سروش.
> توی readme نصب لوا برای آرچ نوشتی lua5.2.
> در حالی که توی مخازن آرچ lua52 هست.
> اگه حوصله داشتی عوض کن :)

Thanks for your issue.
